#!/bin/sh

touch /etc/config/example
uci set example.first=first
uci set example.second=second
uci set example.third=third
uci commit

return 0


touch /etc/config/webcam
uci set webcam.latitude=first
uci set webcam.longitude=second
uci set webcam.imageformat=third
uci set webcam.imagesize=third
uci set webcam.imagequality=third
uci set webcam.iso=third
uci set webcam.aperture=third
uci set webcam.shutterspeed=third
uci set webcam.whitebalance=third
uci set webcam.degrees_cf=third
uci set webcam.upload_server=third
uci set webcam.upload_username=third
uci set webcam.upload_password=third
uci set webcam.upload_directory=third
uci commit

return 0
