#!/bin/sh /etc/rc.common
# Webcam Capture Service

START=90
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /bin/sh "usr/bin/capture_service"
    procd_set_param respawn 5000 5 5   # delay, retries, threshold
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
