#!/bin/sh /etc/rc.common
# camera_tl - servizio per time-lapse camera

START=99
STOP=10

USE_PROCD=1

service_trap() {
    procd_open_instance
    procd_close_instance
}

start_service() {
    # legge il timer da UCI
    INTERVAL=$(uci get camera.shooting.time_lapse 2>/dev/null)
    [ -z "$INTERVAL" ] && INTERVAL=600  # fallback se non definito

    procd_open_instance
    procd_set_param command /usr/bin/mio_script.sh
    procd_set_param respawn
    procd_set_param respawn_interval "$INTERVAL"
    procd_close_instance
}





#!/bin/sh /etc/rc.common

START=99
STOP=10

start() {
    echo "Avvio del servizio mioservizio..."
    /usr/bin/webcam_timer &
}

stop() {
    echo "Arresto del servizio mioservizio..."
    # Se lo script crea processi in background, puoi fermarli qui
    pkill -f /usr/bin/webcam_imer
}
